config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  resources :lists, only: [:index, :create, :show, :new] do
    resources :bookmarks, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :comment, presence: true
  validates :list, presence: true
  validates :movie, presence: true
  validates :movie_id, uniqueness: { scope: :list } #means that one movie to one list, can have more than oneS
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many  :bookmarks, dependent: :destroy
  has_many  :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many  :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

# def show
#  @bookmark.list = List.find(params[:list_id])
# end

  def create
  @bookmark = Bookmark.new(bookmark_params)
  @bookmark.list = List.find(params[:list_id])
  # @bookmark.list = @list
  if @bookmark.save
    redirect_to list_path(@bookmark.list)
  else
    render 'list/show', status: :unprocessable_entity # throws a 422 (for Turbo)
  end
  end

  # ]:3000/lists/5
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
  params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new # I can put this in the index and move the form in the index show page
    # you would have to render index in create
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    # to create the instance from the form data
    @list = List.new(list_params)
    if @list.save
      # when it saves -> go to the restaurants show page
      redirect_to lists_path(@list)
    else
      # @lists = List.all add this if you put List.new in index
      # when it doesnt save -> show the form again
      render 'new', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

  private

  def list_params
    # Strong params -> white listing the attributes users can give us in the form
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
  @movie = Movie.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
  <%= form_with model: list do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.submit "Submit", class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Find top <strong>movies</strong> to <strong>have a laugh</strong>!</h1>
    <a class="btn btn-primary mt-3" href="#">Start Here</a>
  </div>
</div>
<div class="container m-5">
  <h1>List of movies</h1>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <h2><%= list.name %></h2>
        <%= link_to '', list_path(list), class: "card-link" %>
      </div>
    <% end %>
  </div>
  <%= link_to "Create",  new_list_path, class:'text-decoration-none text-white btn btn-primary m-3' %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add a list</h1>
  <%= render 'lists/form', list: @list %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png); height: 400px; display: flex; align-items: center; justify-content: center; color: white; text-align: center;">
  <div class="container">
    <h1>Find top <strong>movies</strong> to <strong>have a laugh</strong>!</h1>
    <%= link_to "Search More Movies", lists_path, class: 'btn btn-primary mt-3' %>
  </div>
</div>
<div class="container m-5">
  <div class="d-flex flex-wrap justify-content-center"> <!-- Flexbox container -->
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card text-center m-3" style="width: 18rem;"> <!-- Card for each item -->
        <img src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %> Poster" class="card-img-top" style="height: 250px; object-fit: cover;">
        <%= link_to 'Delete', bookmark_path(bookmark), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }  %>
        <div class="card-body">
          <!-- Updated card name -->
          <h5 class="card-title">Details: <%= bookmark.movie.title %></h5>
          <p class="card-text"><strong>Comment:</strong> <%= bookmark.comment %></p>
          <p class="card-text"><strong>Rating:</strong> <%= bookmark.movie.rating %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="container m-5">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit "Submit", class: 'btn btn-primary mt-3' %>
    <%= link_to "Home", lists_path, class: 'btn btn-primary mt-3' %>
  <% end %>
</div>